[package]
name = "micro_timer_native"
version = "0.1.0"
edition = "2022"
author = "Massimo Ronca <mr@massimoronca.it>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "timer"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"